config/routes.rb
Rails.application.routes.draw do
  resources :user_accounts
  resources :cover_sheets
  resources :report_subtotals
  resources :travels
  resources :monetary_contributions
  resources :non_monetary_contributions
  resources :pledges
  resources :loans
  resources :expenditures
  resources :unpaid_incurred_obligations
  resources :investment_purchases
  resources :coh_payments
  resources :credits
  resources :reports
  resources :payment_methods
  resources :transactions
  resources :expend_types
  resources :expenditure_categories
  resources :report_types
  resources :election_types
  resources :address_types
  resources :treasurers
  resources :office_soughts
  resources :office_helds
  resources :filer_types
  resources :filers
  resources :candidates
  resources :entity_types
  resources :prefixes
  resources :states
  resources :entities

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
end

app/models/coh_payment.rb
class CohPayment < ActiveRecord::Base
end

app/models/cover_sheet.rb
class CoverSheet < ActiveRecord::Base
  belongs_to :treasurer
end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/entity_type.rb
class EntityType < ActiveRecord::Base
end

app/models/expend_type.rb
class ExpendType < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
end

app/models/filer.rb
class Filer < ActiveRecord::Base
end

app/models/filer_type.rb
class FilerType < ActiveRecord::Base
end

app/models/loan.rb
class Loan < ActiveRecord::Base
end

app/models/non_monetary_contribution.rb
class NonMonetaryContribution < ActiveRecord::Base
end

app/models/office_held.rb
class OfficeHeld < ActiveRecord::Base
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/travel.rb
class Travel < ActiveRecord::Base
end

app/models/treasurer.rb
class Treasurer < ActiveRecord::Base
  has_many :cover_sheets
end

app/controllers/non_monetary_contributions_controller.rb
class NonMonetaryContributionsController < ApplicationController
  before_action :set_non_monetary_contribution, only: [:show, :edit, :update, :destroy]

  # GET /non_monetary_contributions
  # GET /non_monetary_contributions.json
  def index
    @non_monetary_contributions = NonMonetaryContribution.all
  end

  # GET /non_monetary_contributions/1
  # GET /non_monetary_contributions/1.json
  def show
  end

  # GET /non_monetary_contributions/new
  def new
    @non_monetary_contribution = NonMonetaryContribution.new
  end

  # GET /non_monetary_contributions/1/edit
  def edit
  end

  # POST /non_monetary_contributions
  # POST /non_monetary_contributions.json
  def create
    @non_monetary_contribution = NonMonetaryContribution.new(non_monetary_contribution_params)

    respond_to do |format|
      if @non_monetary_contribution.save
        format.html { redirect_to @non_monetary_contribution, notice: 'Non monetary contribution was successfully created.' }
        format.json { render :show, status: :created, location: @non_monetary_contribution }
      else
        format.html { render :new }
        format.json { render json: @non_monetary_contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /non_monetary_contributions/1
  # PATCH/PUT /non_monetary_contributions/1.json
  def update
    respond_to do |format|
      if @non_monetary_contribution.update(non_monetary_contribution_params)
        format.html { redirect_to @non_monetary_contribution, notice: 'Non monetary contribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @non_monetary_contribution }
      else
        format.html { render :edit }
        format.json { render json: @non_monetary_contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /non_monetary_contributions/1
  # DELETE /non_monetary_contributions/1.json
  def destroy
    @non_monetary_contribution.destroy
    respond_to do |format|
      format.html { redirect_to non_monetary_contributions_url, notice: 'Non monetary contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_non_monetary_contribution
      @non_monetary_contribution = NonMonetaryContribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def non_monetary_contribution_params
      params.require(:non_monetary_contribution).permit(:report_id, :transaction_id, :entity_id, :entity_type_id, :travel_id, :candidate_id, :date, :out_of_state_pac, :pac_id, :amount, :description, :date_created, :nmc_total)
    end
end

app/helpers/non_monetary_contributions_helper.rb
module NonMonetaryContributionsHelper
end

app/views/non_monetary_contributions/_form.html.erb
<%= form_for(@non_monetary_contribution) do |f| %>
  <% if @non_monetary_contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@non_monetary_contribution.errors.count, "error") %> prohibited this non_monetary_contribution from being saved:</h2>

      <ul>
      <% @non_monetary_contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :report_id %><br>
    <%= f.number_field :report_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br>
    <%= f.number_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :entity_id %><br>
    <%= f.number_field :entity_id %>
  </div>
  <div class="field">
    <%= f.label :entity_type_id %><br>
    <%= f.number_field :entity_type_id %>
  </div>
  <div class="field">
    <%= f.label :travel_id %><br>
    <%= f.number_field :travel_id %>
  </div>
  <div class="field">
    <%= f.label :candidate_id %><br>
    <%= f.number_field :candidate_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :out_of_state_pac %><br>
    <%= f.check_box :out_of_state_pac %>
  </div>
  <div class="field">
    <%= f.label :pac_id %><br>
    <%= f.number_field :pac_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :date_created %><br>
    <%= f.date_select :date_created %>
  </div>
  <div class="field">
    <%= f.label :nmc_total %><br>
    <%= f.text_field :nmc_total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/non_monetary_contributions/edit.html.erb
<h1>Editing Non Monetary Contribution</h1>

<%= render 'form' %>

<%= link_to 'Show', @non_monetary_contribution %> |
<%= link_to 'Back', non_monetary_contributions_path %>

app/views/non_monetary_contributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Non Monetary Contributions</h1>

<table>
  <thead>
    <tr>
      <th>Report</th>
      <th>Transaction</th>
      <th>Entity</th>
      <th>Entity type</th>
      <th>Travel</th>
      <th>Candidate</th>
      <th>Date</th>
      <th>Out of state pac</th>
      <th>Pac</th>
      <th>Amount</th>
      <th>Description</th>
      <th>Date created</th>
      <th>Nmc total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @non_monetary_contributions.each do |non_monetary_contribution| %>
      <tr>
        <td><%= non_monetary_contribution.report_id %></td>
        <td><%= non_monetary_contribution.transaction_id %></td>
        <td><%= non_monetary_contribution.entity_id %></td>
        <td><%= non_monetary_contribution.entity_type_id %></td>
        <td><%= non_monetary_contribution.travel_id %></td>
        <td><%= non_monetary_contribution.candidate_id %></td>
        <td><%= non_monetary_contribution.date %></td>
        <td><%= non_monetary_contribution.out_of_state_pac %></td>
        <td><%= non_monetary_contribution.pac_id %></td>
        <td><%= non_monetary_contribution.amount %></td>
        <td><%= non_monetary_contribution.description %></td>
        <td><%= non_monetary_contribution.date_created %></td>
        <td><%= non_monetary_contribution.nmc_total %></td>
        <td><%= link_to 'Show', non_monetary_contribution %></td>
        <td><%= link_to 'Edit', edit_non_monetary_contribution_path(non_monetary_contribution) %></td>
        <td><%= link_to 'Destroy', non_monetary_contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Non monetary contribution', new_non_monetary_contribution_path %>

app/views/non_monetary_contributions/new.html.erb
<h1>New Non Monetary Contribution</h1>

<%= render 'form' %>

<%= link_to 'Back', non_monetary_contributions_path %>

app/views/non_monetary_contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Report:</strong>
  <%= @non_monetary_contribution.report_id %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @non_monetary_contribution.transaction_id %>
</p>

<p>
  <strong>Entity:</strong>
  <%= @non_monetary_contribution.entity_id %>
</p>

<p>
  <strong>Entity type:</strong>
  <%= @non_monetary_contribution.entity_type_id %>
</p>

<p>
  <strong>Travel:</strong>
  <%= @non_monetary_contribution.travel_id %>
</p>

<p>
  <strong>Candidate:</strong>
  <%= @non_monetary_contribution.candidate_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @non_monetary_contribution.date %>
</p>

<p>
  <strong>Out of state pac:</strong>
  <%= @non_monetary_contribution.out_of_state_pac %>
</p>

<p>
  <strong>Pac:</strong>
  <%= @non_monetary_contribution.pac_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @non_monetary_contribution.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @non_monetary_contribution.description %>
</p>

<p>
  <strong>Date created:</strong>
  <%= @non_monetary_contribution.date_created %>
</p>

<p>
  <strong>Nmc total:</strong>
  <%= @non_monetary_contribution.nmc_total %>
</p>

<%= link_to 'Edit', edit_non_monetary_contribution_path(@non_monetary_contribution) %> |
<%= link_to 'Back', non_monetary_contributions_path %>