config/routes.rb
Rails.application.routes.draw do
  resources :user_accounts
  resources :cover_sheets
  resources :report_subtotals
  resources :travels
  resources :monetary_contributions
  resources :non_monetary_contributions
  resources :pledges
  resources :loans
  resources :expenditures
  resources :unpaid_incurred_obligations
  resources :investment_purchases
  resources :coh_payments
  resources :credits
  resources :reports
  resources :payment_methods
  resources :transactions
  resources :expend_types
  resources :expenditure_categories
  resources :report_types
  resources :election_types
  resources :address_types
  resources :treasurers
  resources :office_soughts
  resources :office_helds
  resources :filer_types
  resources :filers
  resources :candidates
  resources :entity_types
  resources :prefixes
  resources :states
  resources :entities

end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
end

app/models/coh_payment.rb
class CohPayment < ActiveRecord::Base
end

app/models/cover_sheet.rb
class CoverSheet < ActiveRecord::Base
  belongs_to :treasurer
end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/entity_type.rb
class EntityType < ActiveRecord::Base
end

app/models/expend_type.rb
class ExpendType < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
end

app/models/filer.rb
class Filer < ActiveRecord::Base
end

app/models/filer_type.rb
class FilerType < ActiveRecord::Base
end

app/models/loan.rb
class Loan < ActiveRecord::Base
end

app/models/office_held.rb
class OfficeHeld < ActiveRecord::Base
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
end

app/models/prefix.rb
class Prefix < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/travel.rb
class Travel < ActiveRecord::Base
end

app/models/treasurer.rb
class Treasurer < ActiveRecord::Base
  has_many :cover_sheets
end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:filer_id, :report_type_id, :submit_date, :file_name, :origin, :campaign_year, :upload_type, :on_time, :validity, :signature)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filer_id %><br>
    <%= f.number_field :filer_id %>
  </div>
  <div class="field">
    <%= f.label :report_type_id %><br>
    <%= f.number_field :report_type_id %>
  </div>
  <div class="field">
    <%= f.label :submit_date %><br>
    <%= f.date_select :submit_date %>
  </div>
  <div class="field">
    <%= f.label :file_name %><br>
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :campaign_year %><br>
    <%= f.date_select :campaign_year %>
  </div>
  <div class="field">
    <%= f.label :upload_type %><br>
    <%= f.text_field :upload_type %>
  </div>
  <div class="field">
    <%= f.label :on_time %><br>
    <%= f.check_box :on_time %>
  </div>
  <div class="field">
    <%= f.label :validity %><br>
    <%= f.check_box :validity %>
  </div>
  <div class="field">
    <%= f.label :signature %><br>
    <%= f.text_field :signature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<table>
  <thead>
    <tr>
      <th>Filer</th>
      <th>Report type</th>
      <th>Submit date</th>
      <th>File name</th>
      <th>Origin</th>
      <th>Campaign year</th>
      <th>Upload type</th>
      <th>On time</th>
      <th>Validity</th>
      <th>Signature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.filer_id %></td>
        <td><%= report.report_type_id %></td>
        <td><%= report.submit_date %></td>
        <td><%= report.file_name %></td>
        <td><%= report.origin %></td>
        <td><%= report.campaign_year %></td>
        <td><%= report.upload_type %></td>
        <td><%= report.on_time %></td>
        <td><%= report.validity %></td>
        <td><%= report.signature %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filer:</strong>
  <%= @report.filer_id %>
</p>

<p>
  <strong>Report type:</strong>
  <%= @report.report_type_id %>
</p>

<p>
  <strong>Submit date:</strong>
  <%= @report.submit_date %>
</p>

<p>
  <strong>File name:</strong>
  <%= @report.file_name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @report.origin %>
</p>

<p>
  <strong>Campaign year:</strong>
  <%= @report.campaign_year %>
</p>

<p>
  <strong>Upload type:</strong>
  <%= @report.upload_type %>
</p>

<p>
  <strong>On time:</strong>
  <%= @report.on_time %>
</p>

<p>
  <strong>Validity:</strong>
  <%= @report.validity %>
</p>

<p>
  <strong>Signature:</strong>
  <%= @report.signature %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>